## GitHub 연동

아래 코드를 실행해주세요.


In [ ]:
cd /content/drive/MyDrive/dataScience/datascience/

/content/drive/MyDrive/dataScience/datascience


In [ ]:
!git config --global user.email 'jinjins0629@gmail.com'
!git config --global user.name 'ohhu-code'

In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   Lab1.ipynb
	modified:   Lab2.ipynb

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Lab1.ipynb
	modified:   Lab2.ipynb



In [ ]:
!git pull origin main

remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0 (from 0)
Unpacking objects: 100% (4/4), 1.43 KiB | 1024 bytes/s, done.
From https://github.com/ohhu-code/datascience
 * branch            main       -> FETCH_HEAD
error: cannot lock ref 'refs/remotes/origin/main': is at 6693398874bf7a1e9d60e6a08e7585c05257d170 but expected c57bce5d6ea078647483cf12d1ff72c91e9dd0b1
 ! c57bce5..6693398  main       -> origin/main  (unable to update local ref)


In [ ]:
import pandas as pd
exam_xls = pd.read_excel('/content/drive/MyDrive/dataScience/excel_exam.xlsx')
print(exam_xls)

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58


## Lab4

NumPy: Multidimensional Arrays – zeros(), shape
배열의 차원에 대해서...

In [ ]:
import numpy as np

x = np.zeros(9)
y = np.zeros((4, 5))
z = np.zeros((3, 4, 5))

print(x)
print(y)
print(z)

print(x.shape)
print(y.shape)
print(z.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
(9,)
(4, 5)
(3, 4, 5)


### Git Upload

In [ ]:
!git add .
!git commit -m "Lab4/Dimensions of the Array"

[main da7a0ac] Lab4/Dimensions of the Array
 3 files changed, 2 insertions(+), 2 deletions(-)
 rewrite Lab1.ipynb (97%)
 create mode 100644 Lab2.ipynb
 delete mode 100644 Untitled0.ipynb


In [ ]:
!git push

Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 3.76 KiB | 275.00 KiB/s, done.
Total 4 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/ohhu-code/datascience.git
   233a501..da7a0ac  main -> main


In [ ]:
!git pull origin main

From https://github.com/ohhu-code/datascience
 * branch            main       -> FETCH_HEAD
Already up to date.


In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


## Lab5

full(), ndim, shape, size

In [ ]:
import numpy as np

x = np.full(2, 5)
y = np.full((3, 4), fill_value=1)
z = np.full((3, 4, 5), fill_value=3)

print("ndim = ", x.ndim, y.ndim, z.ndim)
print("shape = ", x.shape, y.shape, z.shape)
print("size = ", x.size, y.size, z.size)

ndim =  1 2 3
shape =  (2,) (3, 4) (3, 4, 5)
size =  2 12 60


### Git Upload

In [ ]:
!git add .
!git commit -m "Lab5/Creating an array with Initialization"

[main cfa7b6b] Lab5/Creating an array with Initialization
 1 file changed, 1 insertion(+), 1 deletion(-)


In [ ]:
!git push

Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.37 KiB | 108.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/ohhu-code/datascience.git
   da7a0ac..cfa7b6b  main -> main


In [ ]:
!git pull origin main

From https://github.com/ohhu-code/datascience
 * branch            main       -> FETCH_HEAD
Already up to date.


In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


## Lab6

eye()

In [ ]:
import numpy as np

x = np.eye(2)
y = np.eye(3)
z = np.eye(3, 4)

print(x)
print(y)
print(z)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


### Git Upload

In [ ]:
!git add .
!git commit -m "Lab6/단위 행렬 함수"

[main e38fffc] Lab6/단위 행렬 함수
 1 file changed, 1 insertion(+), 1 deletion(-)


In [ ]:
!git push

Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 1.18 KiB | 100.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/ohhu-code/datascience.git
   cfa7b6b..e38fffc  main -> main


In [ ]:
!git pull origin main

From https://github.com/ohhu-code/datascience
 * branch            main       -> FETCH_HEAD
Already up to date.


In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean


## Lab7

Array Operations

In [ ]:
import numpy as np

A = np.array([1, 3, 5, 7, 9])
print(A*2)
print(A)
A = A*0.25
print(A)

[ 2  6 10 14 18]
[1 3 5 7 9]
[0.25 0.75 1.25 1.75 2.25]


In [ ]:
import numpy as np

A = np.array([[1, 3, 5], [7, 9, 11]])

B = np.array([[2, 4, 6], [8, 10, 12]])

print(A+B)
print(A-B)
print(A*B)
print(A/B)

[[ 3  7 11]
 [15 19 23]]
[[-1 -1 -1]
 [-1 -1 -1]]
[[  2  12  30]
 [ 56  90 132]]
[[0.5        0.75       0.83333333]
 [0.875      0.9        0.91666667]]


In [ ]:
import numpy as np

asset = np.array([1000,2000,1500,900])
debt = np.array([300,1200,0,1500])
print("asset", asset)
print("debt ", debt)

asset = asset - 500
print("500 deducted each: ")
print("asset", asset)

print("balance after debt deduction: ")
balance = asset - debt

print("balance", balance)
print("balances over 500: ")
print(balance > 500)

asset = balance
debt = debt - debt

print("asset", asset[0], asset[1], asset[2], asset[3])
print("debt ", debt)

asset [1000 2000 1500  900]
debt  [ 300 1200    0 1500]
500 deducted each: 
asset [ 500 1500 1000  400]
balance after debt deduction: 
balance [  200   300  1000 -1100]
balances over 500: 
[False False  True False]
asset 200 300 1000 -1100
debt  [0 0 0 0]


### Git Upload

In [ ]:
!git add .
!git commit -m "Lab7/Array Operations"

[main 3d6936c] Lab7/Array Operations
 2 files changed, 2 insertions(+), 1 deletion(-)
 rewrite Lab2.ipynb (94%)
 create mode 100644 Lab3.ipynb


In [ ]:
!git push

Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 2 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 2.59 KiB | 60.00 KiB/s, done.
Total 4 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/ohhu-code/datascience.git
   4199d63..3d6936c  main -> main


In [ ]:
!git pull origin main

From https://github.com/ohhu-code/datascience
 * branch            main       -> FETCH_HEAD
Already up to date.


In [ ]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
